name: .NET 6 API Deployment

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Publish build
        run: dotnet publish -c Release -o publish

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.SERVER_HOST }}" >> ~/.ssh/known_hosts

      - name: Ensure target directory exists on server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
            "mkdir -p /home/cpsadmin/Deployments/HiApi"

      - name: Copy published files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "publish/*"
          target: /home/cpsadmin/Presentaion/TestAPICICD
          strip_components: 1

      # - name: Restart API service on server
      #   run: |
      #     ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa \
      #       ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
      #       "sudo systemctl restart TestAPICICD || echo 'Service not found, skipping...'"
